name: Deploy

on:
  workflow_run:
    workflows: ["Cypress Tests"]
    types:
      - completed

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    environment:
      name: ULU
    
    steps:
    - name: install ssh keys
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
    - name: deploy
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd /var/www/unrated && rm -f package-lock && git checkout master && git pull && /home/ulu/.nvm/versions/node/v20.11.1/bin/npm i && /home/ulu/.nvm/versions/node/v20.11.1/bin/npm build && systemctl restart ua-frontend && exit"
    - name: cleanup
      run: rm -rf ~/.ssh
